### ISSUE TITLE
confused a bit of send_cmd

### ISSUE THREAD

**Issue by NextWork123** [rrroyal/voltronic-mqtt#1]
Hello, could you better explain how we can send commands such as changing the battery charging settings and SBU or SUB? Previously, I created an automation using the older Docker version of ned-kelly to send commands like MCHGC050 and POP02. Additionally, if we want to run it as a standalone application, is it possible to set it up as a systemd service?

Best Regards

**Comment by rrroyal** [comment]
> how we can send commands

send a message to `$MQTT_TOPIC/$MQTT_TOPIC_SUB` (i.e. `MQTT_TOPIC=homeassistant/sensor/voltronic`, `MQTT_TOPIC_SUB=_cmd` = `homeassistant/sensor/voltronic/_cmd`) with your command as payload (i.e. `POP02`)

> is it possible to set it up as a systemd service

you sure can, just create an entrypoint with your config (like in `standalone.sh`) and set it up as a service :)

**Comment by NextWork123** [comment]
> > how we can send commands
> 
> send a message to `$MQTT_TOPIC/$MQTT_TOPIC_SUB` (i.e. `MQTT_TOPIC=homeassistant/sensor/voltronic`, `MQTT_TOPIC_SUB=_cmd` = `homeassistant/sensor/voltronic/_cmd`) with your command as payload (i.e. `POP02`)
> 
> > is it possible to set it up as a systemd service
> 
> you sure can, just create an entrypoint with your config (like in `standalone.sh`) and set it up as a service :)

oh ok, thanks for the fast reply i will try in these days your project because i need to switch my entire mini pc to arch linux and was searching a project alternative to don't use docker! seem good your work thanks 

so if i'm not wrong on home assistant for send it gonna be like that?

![immagine](https://github.com/user-attachments/assets/2643629a-fd85-4d4f-bcdb-9c73c6f43f76)

**Comment by rrroyal** [comment]
yes, it should work :)

this is the same thing configured as a `select` entity, maybe you'll find it useful:
```yaml
select:
  - unique_id: "voltronic_output_source_priority"
    name: "voltronic_output_source_priority"
    state_topic: "homeassistant/sensor/voltronic/qpiri"
    value_template: >-
      {% set options = ["Utility First", "Solar First", "SBU"] %}
      0{{ value_json.output_source_priority }} ({{ options[value_json.output_source_priority] }})
    command_topic: "homeassistant/sensor/voltronic/_cmd"
    command_template: POP{{ value[:2] }}
    options:
      - "00 (Utility First)"
      - "01 (Solar First)"
      - "02 (SBU)"
```
